import { motion } from 'framer-motion'; // eslint-disable-line no-unused-vars
import { Share2, Copy, Mail, CheckCircle, Flame } from 'lucide-react';
import { useState } from 'react';
import { useApp } from '../store/AppContext';
import { useTheme } from '../store/ThemeContext';
import Logo from '../components/Logo';
import OrgLogo from '../components/OrgLogo';
import { monthsGiving, DEMO_USER, FIRST_MONTH_LABEL } from '../data/derived';
import { fmtMoney } from '../lib/format';
import { copyText } from '../lib/clipboard';

export default function Share() {
  const { selectedNonprofit, totalDonated, showToast, demoActive } = useApp();
  const brand = useTheme();
  const [copied, setCopied] = useState(false);
  const [copyFailed, setCopyFailed] = useState(false);
  const [codeCopied, setCodeCopied] = useState(false);
  const [codeCopyFailed, setCodeCopyFailed] = useState(false);

  if (!selectedNonprofit) return null;

  const orgCode = selectedNonprofit.id?.toUpperCase() ?? 'BGCA';
  // referralCode lives near DEMO_USER  -  in production it is generated by the backend per user
  const referralCode = DEMO_USER.referralCode;
  // shareUrl is the functional deep-link; displayUrl is a shortened form for display only.
  // Copy always copies the full functional URL so it actually works when shared.
  const shareUrl = `https://pocketcache.app/demo/?org=${orgCode}&ref=${referralCode}`;
  const displayUrl = `pocketcache.app/demo/?org=${orgCode.toLowerCase()}&ref=${referralCode.toLowerCase()}`;

  // Legal note: PocketCache is a technology vendor  -  it does not make donations
  // or solicitations. Share copy positions it as the tool, not the benefactor.
  const shareText = `I give to ${selectedNonprofit.name} with every purchase I make  -  spare change that actually adds up. You should try it too. 💙`;

  async function handleCopy() {
    const ok = await copyText(`${shareText}\n${shareUrl}`);
    if (ok) {
      setCopied(true);
      setCopyFailed(false);
      setTimeout(() => setCopied(false), 2000);
    } else {
      setCopyFailed(true);
      setTimeout(() => setCopyFailed(false), 2500);
    }
  }

  async function handleCopyCode() {
    const ok = await copyText(referralCode);
    if (ok) {
      setCodeCopied(true);
      setCodeCopyFailed(false);
      setTimeout(() => setCodeCopied(false), 2000);
    } else {
      setCodeCopyFailed(true);
      setTimeout(() => setCodeCopyFailed(false), 2500);
    }
  }

  // navigator.share is missing on plenty of browsers, and even where it exists
  // the call can reject for a real reason (no share targets registered,
  // permission denied). A user-cancelled share (AbortError) is silent by
  // design - anything else falls back to copying the link, with an honest
  // toast either way.
  async function handleShare() {
    if (navigator.share) {
      try {
        await navigator.share({ title: brand.appName, text: shareText, url: shareUrl });
        return;
      } catch (e) {
        if (e?.name === 'AbortError') return;
        // fall through to the clipboard fallback below
      }
    }
    const ok = await copyText(`${shareText}\n${shareUrl}`);
    showToast(ok ? 'Link copied instead  -  paste it anywhere' : 'Could not share or copy  -  select and copy manually');
  }

  const SHARE_OPTIONS = [
    {
      label: copyFailed ? 'Copy failed  -  try again' : copied ? 'Copied!' : 'Copy Link',
      icon: copied ? <CheckCircle size={20} /> : <Copy size={20} />,
      color: brand.textAccent,
      onPress: handleCopy,
    },
    {
      label: 'Share via...',
      icon: <Share2 size={20} />,
      color: brand.secondary,
      onPress: handleShare,
    },
    {
      label: 'Email a Friend',
      icon: <Mail size={20} />,
      color: brand.textAccent,
      onPress: () => window.open(`mailto:?subject=Join me on ${brand.appName}&body=${encodeURIComponent(shareText + '\n' + shareUrl)}`),
    },
  ];

  return (
    <div className="flex flex-col h-full bg-gray-50">
      <motion.div
        animate={{ background: brand.headerGradient }}
        transition={{ duration: 0.6 }}
        className="px-5 pb-5"
        style={{ paddingTop: 'calc(var(--pc-safe-top) + 12px)' }}
      >
        <h1 className="text-2xl font-bold text-white" style={{ letterSpacing: '-0.3px' }}>Share</h1>
        <p className="text-white/70 text-sm mt-0.5">Spread the word</p>
      </motion.div>

      <div className="flex-1 scrollable pc-scrollbar px-4 pb-28 pt-4 space-y-4">

        {/* Impact card preview */}
        <motion.div
          initial={{ opacity: 0, scale: 0.97 }}
          animate={{ opacity: 1, scale: 1 }}
          className="rounded-3xl overflow-hidden card-shadow"
        >
          <div className="p-6 text-white relative overflow-hidden" style={{ background: brand.gradient }}>
            <div className="absolute top-0 right-0 w-32 h-32 rounded-full bg-white/10 -translate-y-1/2 translate-x-1/3" />
            <div className="relative z-10">
              <div className="flex items-center gap-2 mb-4">
                {brand.brandLogoUrl ? (
                  <div className="w-8 h-8 rounded-xl flex items-center justify-center overflow-hidden bg-white">
                    <img src={brand.brandLogoUrl} alt={brand.appName} className="w-full h-full object-contain p-1" style={{ display: 'block' }} />
                  </div>
                ) : brand.logoEmoji ? (
                  <div className="w-8 h-8 rounded-xl flex items-center justify-center text-base bg-white/20">{brand.logoEmoji}</div>
                ) : <Logo size={28} />}
                <span className="font-bold text-white">{brand.appName}</span>
              </div>
              <p className="text-white/80 text-sm mb-2">I&apos;ve donated</p>
              {/* fmtMoney, not toFixed(2): this card gets screenshotted, and above
                  $999 toFixed rendered "1234.56" while Home read "1,234.56". */}
              <p className="text-5xl font-bold">${fmtMoney(totalDonated)}</p>
              <p className="text-white/80 text-sm mt-2">to {selectedNonprofit.name}</p>
              {/* This card is PUBLIC - a donor sends this link to friends, so it
                  must never show a demo number for a real account. A real
                  account with no charge history yet reads the same honest
                  "first month" framing the dashboards use, with no streak
                  badge; demo mode keeps the streak, clearly labeled, exactly
                  like everywhere else the same demo total shows up. */}
              {!demoActive ? (
                <p className="text-white/70 text-xs mt-3">{FIRST_MONTH_LABEL}</p>
              ) : (
                <div className="mt-3 inline-flex items-center gap-1.5 bg-white/20 rounded-full px-3 py-1">
                  <Flame size={13} className="text-amber-300" />
                  <span className="text-white/90 text-xs font-semibold">{monthsGiving}-month giving streak · Demo data</span>
                </div>
              )}
              <div className="mt-3 pt-4 border-t border-white/20">
                <p className="text-white/70 text-xs">{selectedNonprofit.impact}</p>
              </div>
            </div>
          </div>
          <div className="bg-white px-5 py-3 flex items-center gap-2">
            {/* The real org logo, like every other screen  -  not the raw emoji */}
            <OrgLogo nonprofit={selectedNonprofit} size={7} rounded="lg" />
            <p className="text-gray-500 text-xs flex-1">Spare change from every purchase  -  it adds up. 💙</p>
          </div>
        </motion.div>

        {/* Share message preview */}
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="bg-white rounded-3xl p-5 card-shadow"
        >
          <p className="text-gray-400 text-xs font-semibold uppercase tracking-widest mb-3">Message Preview</p>
          <p className="text-gray-700 text-sm leading-relaxed">{shareText}</p>
          {/* displayUrl is a shortened form of shareUrl for readability */}
          <p className="text-sm font-semibold mt-2" style={{ color: brand.textAccent }}>{displayUrl}</p>
        </motion.div>

        {/* Share buttons */}
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.15 }}
          className="bg-white rounded-3xl overflow-hidden card-shadow"
        >
          {SHARE_OPTIONS.map((opt, i) => (
            <div key={opt.label}>
              <motion.button
                whileTap={{ scale: 0.98 }}
                onClick={opt.onPress}
                className="w-full flex items-center gap-4 px-5 py-4 text-left"
              >
                <div className="w-10 h-10 rounded-2xl flex items-center justify-center"
                  style={{ background: opt.color + '18', color: opt.color }}>
                  {opt.icon}
                </div>
                <p className="font-semibold text-gray-900 text-sm">{opt.label}</p>
              </motion.button>
              {i < SHARE_OPTIONS.length - 1 && <div className="h-px bg-gray-50 mx-5" />}
            </div>
          ))}
        </motion.div>

        {/* Referral  -  fee waiver framing (not donation framing).
            PocketCache is a tech vendor; it cannot make donations on behalf of users
            without triggering charitable solicitation classification. */}
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
          className="rounded-3xl p-5 text-white"
          style={{ background: brand.gradient }}
        >
          <p className="font-bold text-base mb-1">Invite a Friend</p>
          <p className="text-white/80 text-sm leading-relaxed mb-4">
            When someone joins with your link, we waive their first month&apos;s $1 app fee  - 
            so their very first charge is pure giving to {selectedNonprofit.name}.
          </p>
          <div className="bg-white/20 rounded-2xl px-4 py-3 flex items-center justify-between">
            <span className="font-mono text-white font-bold tracking-wider text-sm">{referralCode}</span>
            <button
              onClick={handleCopyCode}
              className="bg-white/20 rounded-xl px-3 py-1.5 text-white text-xs font-semibold"
              title={codeCopyFailed ? 'Copy failed  -  select and copy manually' : undefined}
            >
              {codeCopied ? 'Copied!' : codeCopyFailed ? 'Try again' : 'Copy code'}
            </button>
          </div>
        </motion.div>

      </div>
    </div>
  );
}
